export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  TASKS: '/tasks',
  TASK: (id: number) => `/tasks/${id}`,
  NOTES: '/notes',
  NOTE: (id: number) => `/notes/${id}`,
  CATEGORIES: '/categories',
  QUIZ: (id: number) => `/quizzes/${id}`,
  FOCUS: '/focus',
  ANALYTICS: '/analytics',
  AI_CHAT: '/ai-chat',
  LESSON_PLANS: '/lesson-plans',
  LESSON_PLAN_NEW: '/lesson-plans/new',
  LESSON_PLAN: (id: number) => `/lesson-plans/${id}`,
  LESSON_PLAN_EDIT: (id: number) => `/lesson-plans/${id}/edit`,
} as const;
